name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      ECR_REPOSITORY: helloworld
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: shivali-devops_helloworld-devops-poc
          SONAR_ORGANIZATION: shivali-org

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # DockerHub Login
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ECR Login
      - name: Log in to Amazon ECR
        uses: docker/login-action@v2
        with:
          registry: 664418995582.dkr.ecr.ap-south-1.amazonaws.com
          username: AWS
          password: ${{ secrets.AWS_ECR_PASSWORD }}

      # Build and Push to Both DockerHub and ECR
      - name: Build and push to DockerHub and ECR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            shivali557/helloworld:latest
            664418995582.dkr.ecr.ap-south-1.amazonaws.com/helloworld:latest
